"""技术指标名称映射常量"""

INDICATOR_NAMES = {
    'ATR': 'ATR波动异常',
    'PRICE': '价格变化异常',
    'VOLUME': '成交量异常',
    'BB_WIDTH': '布林带宽度异常',
    'BB_BREAKOUT': '布林带突破',
    'ENGULFING': '外包线',
    'RSI_OVERBOUGHT': 'RSI超买',
    'RSI_OVERSOLD': 'RSI超卖',
    'RSI_ZSCORE': 'RSI异常',
    'BB_UPPER': '布林带上轨突破',
    'BB_LOWER': '布林带下轨突破',
    'BB_BREAKOUT_UPPER': '布林带上轨突破',
    'BB_BREAKOUT_LOWER': '布林带下轨突破',
    'BB_SQUEEZE': '布林带收窄',
    'BB_SQUEEZE_EXPAND': '布林带挤压后扩张',
    'BB_WIDTH_ZSCORE': '布林带宽度异常',
    'MA_DEVIATION': '均线乖离',
    'MA_DEVIATION_ZSCORE': '均线乖离异常',
    'MA_CROSS_GOLDEN': '均线金叉',
    'MA_CROSS_DEATH': '均线死叉',
    'MA_BULLISH_CROSS': '均线金叉',
    'MA_BEARISH_CROSS': '均线死叉',
    'OI_SURGE': '持仓量激增',
    'OI_DROP': '持仓量骤降',
    'OI_ZSCORE': '持仓量异常',
    'OI_MOMENTUM': '持仓量动量异常',
    'OI_DIVERGENCE': '持仓量背离',
    'OI_BULLISH_DIVERGENCE': '持仓量看涨背离',
    'OI_BEARISH_DIVERGENCE': '持仓量看跌背离',
    'LONG_UPPER_WICK': '长上影线',
    'LONG_LOWER_WICK': '长下影线',
}
